[package]
name = "Assignment1"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.5.0"
regex = "1.11.1"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.135"

[dependencies.stem]
git = "https://github.com/minhnhdo/rust-stem"

[features]

setup = []
